### ISSUE TITLE
Bucket names cannot contain forward slashes

### ISSUE THREAD

**Issue by ptvandi** [SeamusJ/deploy-build-to-s3#4]
First off, thank you for the work. This Lambda function has been a huge help.

I noticed when I set the second argument of the `User Parameters` to `true` in order to have the function remove unmatched artifact files, I'm getting the below error in `CodeWatch`. The bucket name I'm passing into the parameters is in the format `<bucket>/<folder>`, which appears to be an issue for the removal method. It appears the upload method works just fine.

**Error**
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): InvalidBucket: Bucket names cannot contain forward slashes`

**Comment by SeamusJ** [comment]
Thanks.

I'll take a look and see if I can find a fix. That's interesting that upload method works just fine.

If you happen to find the bug before I do, just let me know and I'll be happy to merge it in.

**Comment by SeamusJ** [comment]
I'll do some testing tonight, but it looks like an undocumented difference between "s3.deleteObjects()" and "s3.putObject()".

I think this is easy to fix...

**Comment by ptvandi** [comment]
I suspect this issue may have to do with [listObjectsV2](https://github.com/SeamusJ/deploy-build-to-s3/blob/master/src/website.ts#L67) in your `getAWSBucketListing` website method. 

[According to Amazon's documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjectsV2-property), you could use the `Prefix` property for the bucket path to effectively filter the files. You'd have to do something like splitting the bucket name by the first forward-slash and pass the first part as the `Bucket` property and the second part as the `Prefix` property. I'm not sure how using `Prefix` affects truncation and continuation though; if the method will properly return subfolders to iterate through recursively. 

I'm in crunch mode at work so I would't be able to take a stab at this for a while, but I hope this helps some. Thanks again for your efforts.

**Comment by ErgoSoftUK** [comment]
I've submitted a pull request to allow the specifcation of bucket sub-folder.  For putObjects, the sub-folder should be part of the key, not the bucket name.

I also noticed that the Readme.md is missing a permission in the example.  For listObjectsV2, it needs to include the bucket itself as well as the contents.

```
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::example.com",
                "arn:aws:s3:::example.com/*"
            ]
        },
```

**Comment by SeamusJ** [comment]
Pull request merged. Thanks @ErgoSoftUK !
